In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score

In [3]:
df=pd.read_csv("C:/Users/chopp/Downloads/forestfires.csv")

In [4]:
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [5]:
df.drop(['month','day'],axis=1,inplace=True)

In [6]:
array=df.values

In [7]:
array

array([[86.2, 26.2, 94.3, ..., 0, 0, 'small'],
       [90.6, 35.4, 669.1, ..., 1, 0, 'small'],
       [90.6, 43.7, 686.9, ..., 1, 0, 'small'],
       ...,
       [81.6, 56.7, 665.6, ..., 0, 0, 'large'],
       [94.4, 146.0, 614.7, ..., 0, 0, 'small'],
       [79.5, 3.0, 106.7, ..., 0, 0, 'small']], dtype=object)

In [8]:
X=array[:,:-1]
Y=array[:,-1]


In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [10]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((361, 28), (156, 28), (361,), (156,))

In [11]:
clf = SVC()
param_grid = [{'kernel':['linear','rbf','polynomial'],'gamma':[0.5,0.1,0.01],'C':[10,0.1,0.01] }]
gsv = RandomizedSearchCV(clf,param_grid,cv=6,)
gsv.fit(X_train,Y_train)

c:\Users\chopp\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\chopp\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\chopp\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "c:\Users\chopp\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\chopp\anaconda3\Lib\site-packages\

RandomizedSearchCV(cv=6, estimator=SVC(),
                   param_distributions=[{'C': [10, 0.1, 0.01],
                                         'gamma': [0.5, 0.1, 0.01],
                                         'kernel': ['linear', 'rbf',
                                                    'polynomial']}])

In [12]:
gsv.best_params_,gsv.best_score_

({'kernel': 'linear', 'gamma': 0.01, 'C': 10}, 0.9833788706739526)

In [13]:
clf=SVC(kernel='linear',C=10)
clf.fit(X_train,Y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(Y_test,y_pred)*100
print("accuracy =",acc)
confusion_matrix(Y_test,y_pred)

accuracy = 100.0


array([[ 38,   0],
       [  0, 118]], dtype=int64)

In [14]:
confusion_matrix(Y_test,y_pred)

array([[ 38,   0],
       [  0, 118]], dtype=int64)

In [15]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

       large       1.00      1.00      1.00        38
       small       1.00      1.00      1.00       118

    accuracy                           1.00       156
   macro avg       1.00      1.00      1.00       156
weighted avg       1.00      1.00      1.00       156

